MVC_Application/MVC_UI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using BL_Interfaces.Exceptions;
using BusinessEntities;
using BusinessLogics.Properties;
using ControllersResources;
using MVC_UI.Models;
using MVC_UI.Resources.Controllers;
using MVC_UI.Resources.Views;

namespace MVC_UI.Controllers
{
    public class AdminController : BasicController
    {
        [Authorize(Roles = "Administrator")]
        public ActionResult Index()
        {
            return View(Logics.UserAC.All());
        }

        public JsonResult Remove(String name)
        {
            var user = Logics.UserAC.FindByLogin(name, false);
            if(user == null)
            {
                return Json(new {status = "Error", value = new LoginNotFoundException().Message},
                            JsonRequestBehavior.AllowGet);
            }
            var message = user.IsRemoved ? AdminValidation.UserRecoverSuccess : AdminValidation.UserRemoveSuccess; 
            try
            {
                Logics.UserAC.RemoveOrRecoverByAdmin(name);
            }
            catch (Exception e)
            {
                return Json(new {status = "Error", value = e.Message}, JsonRequestBehavior.AllowGet);
            }
            return Json(new {status = "OK", value = message}, JsonRequestBehavior.AllowGet);
        }

        public JsonResult TechTypeahead(String name)
        {
            return Json(new {options = Logics.TechnologyAC.FindTechnologiesContainingText(name).Select(t => t.Name)},
                        JsonRequestBehavior.AllowGet);
        }

        public JsonResult TagTypeahead(String name)
        {
            return Json(new {options = Logics.TagAC.FindTagsContainingText(name).Select(t => t.Text)},
                        JsonRequestBehavior.AllowGet);
        }

        public JsonResult Approve(String name)
        {
            var user = Logics.UserAC.FindByLogin(name, false);
            if (user == null)
            {
                return Json(new { status = "Error", value = new LoginNotFoundException().Message },
                            JsonRequestBehavior.AllowGet);
            }
            var message = user.IsApproved ? AdminPageStrings.UserAlreadyApproved : AdminPageStrings.UserApproveSuccess;
            try
            {
                user.IsApproved = true;
                Logics.Database.UserRepository.AddOrUpdate(user);
            }
            catch (Exception e)
            {
                return Json(new { status = "Error", value = e.Message }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { status = "OK", value = message }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(string name)
        {
            if (!Roles.IsUserInRole("Administrator"))
            {
                return Content(new NoRightsException().Message);
            }
            var user = Logics.UserAC.FindByLogin(name, false);
            var model = new UserModel(user)
                {
                    Languages = Logics.LanguageAC.All().Select(lang => new SelectListItem
                        {
                            Selected = user.Language != null && user.Language.Locale == lang.Locale,
                            Text = lang.Name,
                            Value = lang.Locale,
                        }).ToList(),
                        Password = user.Password.Substring(0, 10),
                        UserId = user.UserId,
                };
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Save(UserModel user)
        {
            var original = Logics.UserAC.Find(user.UserId);
            var substring = original.Password.Substring(0, 10);
            bool passwordChanged = user.Password != substring;
            try
            {
                Logics.UserAC.Edit(user.UserId, user.Login, passwordChanged ? user.Password : null, user.Email);
            }
            catch(Exception e)
            {
                throw new HttpException(502, e.Message);
            }
            return Content(AdminPageStrings.UserEditSuccess);
        }

        public JsonResult ValidateLogin(String login, Guid userId)
        {
            var user = Logics.UserAC.Find(userId);
            if (Logics.UserAC.FindByLogin(login, false) != null && user.Login != login)
            {
                return Json(ValidationStrings.LoginFound, JsonRequestBehavior.AllowGet);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ValidateEmail(String email, Guid userId)
        {
            var user = Logics.UserAC.Find(userId);
            if (Logics.UserAC.FindByMail(email, false) != null && user.Email != email)
            {
                return Json(ValidationStrings.EmailFound, JsonRequestBehavior.AllowGet);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ValidateLanguage(String languageLocale)
        {
            var language = Logics.LanguageAC.Find(languageLocale, false) ??
                           Logics.LanguageAC.FirstOrDefault(l => l.Name == languageLocale);
            if (language == null)
            {
                return Json(AdminValidation.LanguageNotFound, JsonRequestBehavior.AllowGet);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Resend(string name)
        {
            var user = Logics.UserAC.FindByLogin(name, false);
            if (user == null)
            {
                return Json(new {status = "Error", value = new LoginNotFoundException().Message},
                            JsonRequestBehavior.AllowGet);
            }
            var message = user.IsApproved ? AdminPageStrings.MailSendFailed : AdminPageStrings.MailSendSuccess;
            try
            {
                Logics.UserAC.SendVerification(name);
            }
            catch (Exception e)
            {
                return Json(new { status = "Error", value = e.Message }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { status = "OK", value = message }, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult UsersList(int page = 0)
        {
            const int items = 2;
            ViewData["Pager"] = GetPager(items, Logics.UserAC.Count(), page);
            ViewData["Page"] = page;
            var users = Logics.UserAC.GetPageOrderedByAscending(page, items, u => u.Login, u => true);
            return PartialView("List", users);
        }

        public ActionResult TagsCloud()
        {
            var httpCookie = Request.Cookies["language"];
            return PartialView(Logics.TagAC.GetMostPopular(20, httpCookie == null ? "ru" : httpCookie.Value));
        }

        public ActionResult Popular()
        {
            var tasks = Logics.TaskAC.GetPageOrderedByDescending(0, 8, t => t.Likes.Count, t => true);
            return PartialView("Popular", tasks);
        }

        public IEnumerable<Tuple<String, String>> GetPager(int itemsPerPage, int count, int page)
        {
            int pagesCount = (int)Math.Ceiling(1.0f * count / itemsPerPage);
            var res = new List<Tuple<string, string>>();
            if (count != 0)
            {
                if (page > 0 && page < pagesCount)
                {
                    res.Add(new Tuple<string, string>(AdminPageStrings.PrevPage, (page - 1).ToString()));
                }
                for (int i = 0; i < pagesCount; i++)
                {
                    res.Add(new Tuple<string, string>(i.ToString(), i.ToString()));
                }
                if (page > -1 && page < pagesCount - 1)
                {
                    res.Add(new Tuple<string, string>(AdminPageStrings.NextPage, (page + 1).ToString()));
                }
            }
            return res;
        }

        public ActionResult PagedTasks(int page = 0)
        {
            const int items = 3;
            ViewData["Pager"] = GetPager(items, Logics.TaskAC.Count(), page);
            ViewData["Page"] = page;
            var tasks = Logics.TaskAC.GetPageOrderedByDescending(page, items, u => u.PostDate, u => true);
            return PartialView("PagedTasks", tasks);
        }
    }
}

MVC_Application/MVC_UI/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessEntities;
using MVC_UI.Models;
using System.Globalization;
using System.Web.Security;

namespace MVC_UI.Controllers
{
    public class SharedController : BasicController
    {
        //
        // GET: /Shared/
        public ActionResult Index()
        {
            MainModel model = new MainModel();
            model.RecentTasks = Logics.TaskAC.GetPageOrderedByDescending(0, 10, t => t.PostDate, t => true).ToList();

            return View("Main", model);
        }

        public ActionResult Popular()
        {
            List<Task> popularTasks = new List<Task>();
            return View("Tasks", popularTasks);
        }

        public ActionResult Users(string name)
        {
            return View("User", Logics.UserAC.Where(u => u.Login == name).SingleOrDefault());
        }


        public ActionResult Task(string name)
        {
            Task task = Logics.TaskAC.Where(t => t.NameForLink == name).SingleOrDefault();
            return View("Task", new TaskWithAnswerModel(task));
        }

        public PartialViewResult ToAnswer(TaskWithAnswerModel task)
        {
            try
            {
                //if (Logics.CurrentUser.Tasks.Where(t => t.Id == task.Id).Count() != 0)
                //{
                //    ModelState.AddModelError("", ControllersResources.ValidationStrings.YoursTask);
                //}
                if (Logics.TaskAC.TrySolve(task.Id, task.MyAnswer))
                {
                    ViewData["goodans"] = ControllersResources.ValidationStrings.RightAns;
                }
                else
                {
                    ModelState.AddModelError("", ControllersResources.ValidationStrings.WrongAns);
                }
                return PartialView("Answer", task);
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return PartialView("Answer", task);
            }
        }

        public ActionResult Tag(string name)
        {
            return View("Tasks", Logics.TaskAC.Where(t => t.Tags
                .FirstOrDefault(tag => tag.Text.Contains(name)) != null).ToList());
                //.Tags.Select(g => g.Text).Contains(name)));
        }

        public ActionResult Technology(string name)
        {
            return View("Tasks", Logics.TaskAC.Where(t => t.Technology.Name == name).ToList());
        }

        public ContentResult Like(Guid id)
        {
            return Content(Logics.TaskAC.Like(id).ToString());
        }

        public ActionResult Search(String searchText)
        {
            return View("Tasks", Logics.TaskAC.Find(searchText));
        }

        public ActionResult Language(string returnUrl, string language)
        {
            Response.AppendCookie( new HttpCookie("language", language));
            return Redirect(returnUrl);
        }

        #region LOGIN

        public ActionResult Login()
        {
            if (Logics.CurrentUser == null)
                return View("Login", new LoginModel());
            else
                return RedirectToAction("UserTasks", "User");
        }
        
        [HttpPost]
        public ActionResult SignIn(LoginModel model)
        {
            try
            {
                if (Logics.UserAC.FindByLogin(model.Login, true).IsRemoved)
                {
                    return RedirectToAction("RemovedUser");
                }
                if (!Logics.UserAC.FindByLogin(model.Login, true).IsApproved)
                {
                    return RedirectToAction("Authentication");
                }
                Logics.UserAC.LogIn(model.Login, model.Password);
                FormsAuthentication.SetAuthCookie(model.Login, model.RememberMe);
                return RedirectToAction("UserTasks", "User");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("Login", model);
            }
        }

        public ActionResult RemovedUser()
        {
            return View("RemovedUser", new RemovedUserModel());
        }

        [HttpPost]
        public ActionResult Restore(RemovedUserModel model)
        {
            try
            {
                Logics.UserAC.RecoverByUser(model.Login, model.Password);
                FormsAuthentication.SetAuthCookie(model.Login, false);
                return RedirectToAction("UserTasks", "User");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("RemovedUser", model);
            }
        }

        public ActionResult Registration()
        {
            return View("Register", new RegisterModel());
        }

        [HttpPost]
        public ActionResult Register(RegisterModel model)
        {
            try
            {
                Logics.UserAC.Register(model.Login, model.Password, model.Email, false);
                return View("Authentication", new AuthenticationModel());
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("Register", model);
            }
        }

        public ActionResult Authenticate(AuthenticationModel model)
        {
            try
            {
                if (Logics.UserAC.Approve(model.Login, model.Key))
                {
                    FormsAuthentication.SetAuthCookie(model.Login, false);
                    return RedirectToAction("UserTasks", "User");
                }
                else
                {
                    throw new Exception(ControllersResources.ValidationStrings.WrongKey);
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("Authentication", model);
            }
        }

        public ActionResult Authentication()
        {
            return View();
        }

        public JsonResult ValidateLogin(String login)
        {
            if (Logics.UserAC.FindByLogin(login, false) != null)
                return Json(ControllersResources.ValidationStrings.LoginFound, JsonRequestBehavior.AllowGet);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ValidateEmail(String email)
        {
            if (Logics.UserAC.FindByMail(email, false) != null)
                return Json(ControllersResources.ValidationStrings.EmailFound, JsonRequestBehavior.AllowGet);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        #endregion

    }
}

MVC_Application/MVC_UI/Views/Admin/Edit.cshtml
@using MVC_UI.Resources.Views
@model MVC_UI.Models.UserModel

<div class="alert" id="edit-status" style="display:none"></div>

@using (Html.BeginForm("Save", "Admin", FormMethod.Post, new { @class = "form-horizontal", id = "userEditForm" }))
{
    <div class="control-group">
        <label class="control-label">@AdminPageStrings.Login</label>
        <div class="controls">
            @Html.TextBoxFor(m => m.Login, new {placeholder = AdminPageStrings.Login, type = "text"})
            @Html.ValidationMessageFor(m => m.Login)
        </div>
    </div> 

    <div class="control-group">
        <label class="control-label">@AdminPageStrings.Email</label>
        <div class="controls">
            @Html.TextBoxFor(m => m.Email, new {placeholder = AdminPageStrings.Email, type = "email"})
            @Html.ValidationMessageFor(m => m.Email)
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">@AdminPageStrings.Password</label>
        <div class="controls">
            @Html.TextBoxFor(m => m.Password, new {placeholder = AdminPageStrings.Password, type = "password"})
            @Html.ValidationMessageFor(m => m.Password)
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">@ViewsResources.SharedStrings.Language</label>
        <div class="controls">
            @Html.DropDownListFor(m => m.LanguageLocale, Model.Languages)
        </div>
    </div>
    @Html.HiddenFor(m => m.UserId)
    <button type="submit" class="submit-changes btn btn-success" style="margin-left: 180px">@AdminPageStrings.SaveChangesButton</button>
    
}

MVC_Application/MVC_UI/Views/Admin/Index.cshtml
@using MVC_UI.Resources.Views
@using ModelsResources
@using ViewsResources
@model IEnumerable<BusinessEntities.User>

@{
    ViewBag.Title = AdminPageStrings.PageTitle;
}

<script type="text/javascript">
    function loadUsers() {
        $("#result").load("@Url.Action("UsersList")");
    };
    
    function loadPage() {
        var page = $("#page-number").html();
        $("#result").load("@Url.Action("UsersList")" + "/" + page.toString());
    }

    $(function () {
        loadUsers();
        setInterval("loadPage()", 5000);

        $(document).on("submit", "form", function(e) {
            e.preventDefault();
            $.ajax({
                url: this.action,
                type: this.method,
                data: $(this).serialize(),
                success: function (result) {
                    $('#edit-status').show();
                    $('#edit-status').html(result);
                }
            });
            return false;
        });
        
        $(document).on("click", ".page-button", function (e) {
            e.preventDefault();
            var url = $(this).attr("data-url");
            $("#result").load(url);
            return false;
        });

        $(document).on("click", ".approve", function (e) {
            e.preventDefault();
            $.ajax({
                url: $(this).attr("data-url"),
                success: function (data) {
                    $('#myModal').modal('show');
                    $("#error-text").text(data.value);
                }
            });
            return false;
        });

        $(document).on("click", ".remove", function (e) {
            e.preventDefault();
            $.ajax({
                url: $(this).attr("data-url"),
                success: function (data) {
                    $('#myModal').modal('show');
                    $("#error-text").text(data.value);
                }
            });
            return false;
        });

        $(document).on("click", ".edit", function (e) {
            e.preventDefault();
            $('#editUserModal').modal('show');
            $('#editUserBody').load($(this).attr("data-url"), {}, function () {
                $('form').removeData('validator');
                $('form').removeData('unobtrusiveValidation');
                $.validator.unobtrusive.parse('form');
            });
            return false;
        });
    });
</script>

<div class="span11 well">
    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">@AdminPageStrings.UserManageMessage</h3>
        </div>
        <div class="modal-body">
            <p id="error-text"></p>
        </div>
    </div>

    <div id="editUserModal" class="modal hide fade" tabindex="-1" role="dialog"
        aria-labelledby="editUserLabel" aria-hidden="true" style="margin-left: -350px; width: 600px">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="editUserLabel">@AdminPageStrings.EditUserText</h3>
        </div>
        <div id="editUserBody" class="modal-body">
        </div>
    </div>

    <h3>@AdminPageStrings.ListOfUsers</h3>
    <div id="result"></div>
</div>

MVC_Application/MVC_UI/Views/Admin/List.cshtml
@using MVC_UI.Resources.Views
@model IEnumerable<BusinessEntities.User>

@{
    
}

<table class="table table-bordered table-striped">
    <tr>
        <td>@AdminPageStrings.Login</td>
        <td>E-mail</td>
        <td>@AdminPageStrings.IsApproved</td>
        <td>@AdminPageStrings.AdminActions</td>
    </tr>

    @foreach (var user in Model)
    {
        <tr>
            <td>@user.Login</td>
            <td>@user.Email</td>
            <td>
                @if (!user.IsApproved)
                {
                    <button class="btn btn-mini approve btn-info" style="min-width:25px;" 
                            data-url="@Url.Action("Approve", "Admin", new { name = user.Login })">
                        @AdminPageStrings.ApproveUserButton</button>
                }
                else
                {
                    @AdminPageStrings.Yes
                }
            </td>
            <td>
                <div class="btn-group">
                    <button class="btn btn-mini remove @(user.IsRemoved ? "" : "remove btn-danger")" style="min-width: 25px;" 
                            data-url="@Url.Action("Remove", "Admin", new { name = user.Login })">
                        @(user.IsRemoved ? AdminPageStrings.RecoverUserButton : AdminPageStrings.RemoveUserButton)</button>
                    <button class="btn btn-mini edit btn-warning" style="min-width: 25px;" 
                            data-url="@Url.Action("Edit", "Admin", new { name = user.Login })">
                        @AdminPageStrings.EditUserButton</button>
                </div>
            </td>
        </tr>
    }
</table>

@{
    int page = (int) ViewData["Page"];
    }

<span id="page-number" style="display:none;">@page</span>
    
    <div class="pagination">
        <ul>
        @foreach(var tuple in (IEnumerable<Tuple<string, string>>)ViewData["Pager"])
        {
            <li class="@(tuple.Item1 == page.ToString() ? "disabled" : "")"><a class="page-button" href="#" data-url="@Url.Action("UsersList", "Admin", new { page = tuple.Item2 })">@tuple.Item1</a></li>
        }
       </ul>
    </div>

MVC_Application/MVC_UI/Views/Admin/PagedTasks.cshtml
@model System.Collections.Generic.IEnumerable<BusinessEntities.Task>

@{
int page = (int)ViewData["Page"];
}

@{ Html.RenderPartial("TasksPartial", Model); }

<span id="page-number" style="display: none;">@page</span>

<div class="pagination" style="margin-left: 35px;">
    <ul>
        @foreach (var tuple in (IEnumerable<Tuple<string, string>>)ViewData["Pager"])
        {
            string cl = tuple.Item1 == page.ToString() ? "disabled" : "";
                
            <li class="@cl"><a class="page-button" href="#" data-url="@Url.Action("PagedTasks", "Admin", new { page = tuple.Item2 })">@tuple.Item1</a></li>
        }
    </ul>
</div>

MVC_Application/MVC_UI/Views/Admin/Popular.cshtml
@using MVC_UI.Resources.Views
@model System.Collections.Generic.IEnumerable<BusinessEntities.Task>

<div style="margin-top: 35px; margin-left:35px">
    <legend style="color: gray">@AdminPageStrings.PopularTasks</legend>
    <table style="height:310px" class="table table-striped">
    @foreach(var task in Model)
    {
        <tr>
            <td width="190px">@Html.ActionLink(task.Name, "Task", "Shared", new {name = task.NameForLink}, null)</td>
            <td width="70px">@Html.ActionLink(task.Author.Login, "Users", "Shared", new {name = task.Author.Login}, null)</td>
        </tr>
    }
    </table>
</div>